### PR TITLE
Updates build scripts.

### PR DESCRIPTION
**Pull request by pablog**
Update scripts

### CODE REVIEW

**Comment by pablog** [comment]
@danielaRiesgo didn't you have this failure when you updated scripts in wolmo? It seems `check_xcode_version` doesn't have execution permissions.

**Comment by danielaRiesgo** [comment]
I had that problem when I created the PR in scripts, but it was supposedly solved.
@guidomb seems it didn't work.

**Comment by pablog** [comment]
This is weird..

In `ios-scripts` I have: `-rwxr-xr-x  1 pablogiorgi  staff   781 Mar 22 15:57 check_xcode_version`
in the project I have: `-rw-r--r--  1 pablogiorgi  staff   781 May 15 16:56 check_xcode_version`

It seems during the `install` it misses execution permissions. It's the only file in which this happens...

**Comment by woloxci** [comment]
**CodeStats metrics details:**

:white_check_mark: Code Coverage (Slather): 0.0
:white_check_mark: Code Quality (Swiftlint): 100.0


Click [here](http://codestats.wolox.com.ar/organizations/wolox/projects/ios-base-project/branches/update-scripts) for more details.

**Comment by pablog** [comment]
Well, I `chmod ugo+x` the file. It will work, but we should fix it in `ios-scripts`

**Pull request merged**
