### PR TITLE
Rename xcconfig files to capitalized names

### PR DESCRIPTION
**Pull request by pablog**
## Summary ##

Just capitalize xcconfig files just to avoid a `.downcase` in fastlane scripts.

### CODE REVIEW

**Comment by woloxci** [comment]
**CodeStats metrics details:**

:white_check_mark: Code Coverage (Slather): 0.0
:white_check_mark: Code Quality (Swiftlint): 100.0


Click [here](http://codestats.wolox.com.ar/organizations/wolox/projects/ios-base-project/branches/rename-xcconfig) for more details.

**Comment by pablog** [comment]
@danielaRiesgo I didn't find any `.downcase` in `Fastfile`. It will be useful for the scripts I'm working on, but I don't think this should break anything currently working.

**Comment by danielaRiesgo** [comment]
Oh okay, I didn't understood. As the summary says:
> Just capitalize xcconfig files just to avoid a `.downcase` in fastlane scripts.

If you are making them capital, this shouldn't avoid the `.downcase` I think, it should make it necessary, right?

**Comment by pablog** [comment]
Sorry, I wasn't clear. I meant the fastlane scripts I'm working on, not the existing ones xD

**Pull request merged**
