### PR TITLE
Build configurations

### PR DESCRIPTION
**Pull request by danielaRiesgo**
## Summary ##

Solving issue #1.

Adding build configurations, scheme environment variables and Environment enum.

Solving issue #2.

Adding distinct bundle id and app icon set for each build configuration.

## Known issues ##

In UITests, the environment variable needS to be manually set.
The Bundle ID's are not automatically renamed in the renaming process in the kickoff guide. So it should be modified manually.

### CODE REVIEW

**Comment by guidomb** [comment]
:+1:

**Comment by danielaRiesgo** [comment]
I can't merge it @guidomb, I don't have write access.

**Comment by pablog** [comment]
Great @danielaRiesgo!

I don't hace write permission either. Could you @guidomb give me some more privileges?

**Comment by guidomb** [comment]
@epintos is the one with the access credentials to give access. Although remember that all PR should be reviewed before merging them.

**Pull request merged**
